# Generated by Django 5.0.2 on 2024-03-28 01:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.poste')),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('contactinfo', models.CharField(max_length=255)),
            ],
            bases=('StudenHelp.poste',),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.poste')),
                ('localisation', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('contactinfo', models.CharField(max_length=255)),
            ],
            bases=('StudenHelp.poste',),
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.poste')),
                ('text', models.CharField(max_length=255)),
            ],
            bases=('StudenHelp.poste',),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.poste')),
                ('typestg', models.IntegerField()),
                ('societe', models.CharField(max_length=255)),
                ('duree', models.IntegerField()),
                ('sujet', models.CharField(max_length=255)),
                ('contactinfo', models.CharField(max_length=255)),
                ('specialite', models.CharField(max_length=255)),
            ],
            bases=('StudenHelp.poste',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('poste_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.poste')),
                ('depart', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('heure_dep', models.TimeField()),
                ('nbre_sieges', models.IntegerField()),
                ('contactinfo', models.CharField(max_length=255)),
            ],
            bases=('StudenHelp.poste',),
        ),
        migrations.AddField(
            model_name='poste',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudenHelp.user'),
        ),
        migrations.CreateModel(
            name='EvenClub',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.evenement')),
                ('club', models.CharField(max_length=255)),
            ],
            bases=('StudenHelp.evenement',),
        ),
        migrations.CreateModel(
            name='EvenSocial',
            fields=[
                ('evenement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='StudenHelp.evenement')),
                ('prix', models.FloatField()),
            ],
            bases=('StudenHelp.evenement',),
        ),
    ]
