# Generated by Django 5.0.2 on 2024-05-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudenHelp', '0003_poste_image_poste_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reaction',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='poste',
            name='type',
            field=models.IntegerField(choices=[(0, 'offre'), (1, 'demmande')], default=0),
        ),
        migrations.AlterField(
            model_name='stage',
            name='typestg',
            field=models.IntegerField(choices=[(1, 'ouvrier'), (2, 'technicien'), (3, 'PFE')]),
        ),
    ]
