# Generated by Django 4.2.13 on 2024-05-11 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("StudenHelp", "0005_rename_users_poste_uc"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Uuuuu",
        ),
        migrations.AlterField(
            model_name="poste",
            name="uc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="users",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
