# Generated by Django 4.2.13 on 2024-05-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StudenHelp", "0006_rename_user_uuuuu_alter_poste_uc_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Uuuuu",
        ),
    ]
