# Generated by Django 4.2.13 on 2024-05-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudenHelp", "0007_delete_uuuuu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stage",
            name="typestg",
            field=models.IntegerField(
                choices=[(1, "ouvrier"), (2, "technicien"), (3, "PFE")], default=1
            ),
        ),
    ]
