# Generated by Django 5.0.2 on 2024-05-16 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudenHelp', '0008_alter_stage_typestg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='StudenHelp.poste'),
        ),
    ]
