# Generated by Django 4.2.13 on 2024-05-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("StudenHelp", "0009_alter_reaction_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poste",
            options={"ordering": ["-date"]},
        ),
    ]
