# Generated by Django 4.2.13 on 2024-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudenHelp", "0011_alter_poste_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poste",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
