# Generated by Django 4.2.13 on 2024-05-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("StudenHelp", "0012_alter_poste_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transport",
            name="heure_dep",
            field=models.DateTimeField(),
        ),
    ]
